default['chef_aws_provisioning']['vpc']['profile']='default'
default['chef_aws_provisioning']['vpc']['aws_region'] = 'us-east-1'
default['chef_aws_provisioning']['vpc']['vpc_name'] = 'chef_demo'
default['chef_aws_provisioning']['vpc']['cidr_block'] = '10.0.0.0/16'
default['chef_aws_provisioning']['vpc']['cidr_block1'] = '10.0.0.0/24'
default['chef_aws_provisioning']['vpc']['cidr_block2'] = '10.0.2.0/24'
default['chef_aws_provisioning']['vpc']['vpc_az_1'] = 'us-east-1a'
default['chef_aws_provisioning']['vpc']['vpc_az_2'] = 'us-east-1b'
